<svelte:head>
	<title>Create SvelteKit App</title>
	<meta name="description" content="Generated by Create Vite." />
</svelte:head>

<article class="flex min-h-screen flex-col">
	<section class="flex flex-grow flex-col gap-1 px-4 py-5">
		<h1 class="text-4xl font-semibold text-neutral-900">Welcome to SvelteKit</h1>
		<p class="pl-1 text-base tracking-tight text-neutral-600">
			Visit <a
				href="https://kit.svelte.dev"
				class="text-blue-600 outline-none hover:underline focus-visible:underline"
			>
				kit.svelte.dev
			</a> to read the documentation
		</p>
	</section>
</article>
