<script lang="ts">
	import { timeline, type TimelineDefinition } from "motion";
	import type { TransitionConfig } from "svelte/transition";
	import { bounceOut, backIn } from "svelte/easing";

	const duration = 1;

	let checked = $state(false);

	function animIn<T extends HTMLElement>(node: T): TransitionConfig {
		const sequence: TimelineDefinition = [
			[node, { opacity: [0, 1] }, { duration }],
			[
				node,
				{ x: ["100%", "0%"], y: ["100%", "0%"], rotate: [-90, 0] },
				{
					at: "-0.75",
					duration,
					easing: bounceOut,
				},
			],
		];
		const _timeline = timeline(sequence);

		return {
			duration: duration * 1000,
			tick(t) {
				_timeline.currentTime = t;
			},
		};
	}

	function animOut<T extends HTMLElement>(node: T): TransitionConfig {
		const sequence: TimelineDefinition = [
			[
				node,
				{ y: ["0%", "100%"] },
				{
					duration,
					easing: backIn,
				},
			],
			[
				node,
				{ opacity: [1, 0] },
				{
					at: "-0.25",
					duration: duration * 0.25,
				},
			],
		];
		const _timeline = timeline(sequence);

		return {
			duration: duration * 1000,
			tick(_, u) {
				_timeline.currentTime = u;
			},
		};
	}
</script>

<svelte:head>
	<title>Create SvelteKit App</title>
	<meta name="description" content="Generated by Create Vite." />
</svelte:head>

<article class="flex min-h-screen flex-col">
	<section class="flex flex-grow flex-col gap-1 px-4 py-5">
		<label class="flex touch-none select-none items-center gap-1">
			<input type="checkbox" bind:checked />
			Visible
		</label>

		{#if checked}
			<div class="h-28 w-28 bg-neutral-900" in:animIn out:animOut />
		{/if}
	</section>
</article>
